export const LOAD_BEERS_REQUEST = "beers:LOAD_BEERS_REQUEST";
export const LOAD_BEERS_SUCCESS = "beers:LOAD_BEERS_SUCCESS";
export const LOAD_BEERS_FAILURE = "beers:LOAD_BEERS_FAILURE";

export const LOAD_BEER_REQUEST = "beers:LOAD_BEER_REQUEST";
export const LOAD_BEER_SUCCESS = "beers:LOAD_BEER_SUCCESS";
export const LOAD_BEER_FAILURE = "beers:LOAD_BEER_FAILURE";

export const UPDATE_BEERS = "beers:UPDATE_BEERS";
export const UPDATE_BEER = "beers:UPDATE_BEER";

export default {
  LOAD_BEERS_REQUEST,
  LOAD_BEERS_SUCCESS,
  LOAD_BEERS_FAILURE,
  LOAD_BEER_REQUEST,
  LOAD_BEER_SUCCESS,
  LOAD_BEER_FAILURE,
  UPDATE_BEERS,
  UPDATE_BEER
};
